/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen1_sergiosuazo;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Random;
import javax.swing.DefaultComboBoxModel;
/**
 *
 * @author Sergio
 */
public class Tutorias extends javax.swing.JFrame {

    /**
     * Creates new form Tutorias
     */
    public Tutorias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Crear_Usuario = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        tf_userN = new javax.swing.JTextField();
        tf_contra = new javax.swing.JTextField();
        tf_lugar = new javax.swing.JTextField();
        tf_carrera = new javax.swing.JTextField();
        js_edad = new javax.swing.JSpinner();
        js_cuenta = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        cb_tipo = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        TutoresFrame = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tf_nombreM = new javax.swing.JTextField();
        tf_userM = new javax.swing.JTextField();
        tf_contraM = new javax.swing.JTextField();
        tf_lugarM = new javax.swing.JTextField();
        tf_carreraM = new javax.swing.JTextField();
        js_edadM = new javax.swing.JSpinner();
        js_cuentaM = new javax.swing.JSpinner();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_tutores = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        js_enseñanza = new javax.swing.JSpinner();
        jButton7 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        NormalFrame = new javax.swing.JDialog();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        tf_nombreM1 = new javax.swing.JTextField();
        tf_userM1 = new javax.swing.JTextField();
        tf_contraM1 = new javax.swing.JTextField();
        tf_lugarM1 = new javax.swing.JTextField();
        tf_carreraM1 = new javax.swing.JTextField();
        js_edadM1 = new javax.swing.JSpinner();
        js_cuentaM1 = new javax.swing.JSpinner();
        jButton8 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_normal = new javax.swing.JTable();
        jLabel26 = new javax.swing.JLabel();
        js_enseñanza1 = new javax.swing.JSpinner();
        jButton9 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        Examenes = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jt_examenes = new javax.swing.JTable();
        jButton10 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jt_pasados = new javax.swing.JTable();
        Reservar = new javax.swing.JDialog();
        jScrollPane5 = new javax.swing.JScrollPane();
        jt_tutorias = new javax.swing.JTable();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        tf_clase = new javax.swing.JTextField();
        tf_tema = new javax.swing.JTextField();
        cb_tutor = new javax.swing.JComboBox<>();
        dc_fecha = new com.toedter.calendar.JDateChooser();
        js_aula = new javax.swing.JSpinner();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        DarTutoria = new javax.swing.JDialog();
        jScrollPane6 = new javax.swing.JScrollPane();
        jt_misTutos = new javax.swing.JTable();
        jLabel34 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        tf_user = new javax.swing.JTextField();
        pf_contra = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel3.setText("Nombre:");

        jLabel4.setText("Contraseña:");

        jLabel5.setText("N Cuenta: ");

        jLabel6.setText("Edad: ");

        jLabel7.setText("Carrera:");

        jLabel8.setText("Lugar de Nacimiento:");

        jLabel9.setText("Usuario: ");

        jLabel10.setText("Tipo de Cuenta: ");

        cb_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tutor", "Estudiante" }));

        jButton4.setText("Crear");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Crear_UsuarioLayout = new javax.swing.GroupLayout(Crear_Usuario.getContentPane());
        Crear_Usuario.getContentPane().setLayout(Crear_UsuarioLayout);
        Crear_UsuarioLayout.setHorizontalGroup(
            Crear_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Crear_UsuarioLayout.createSequentialGroup()
                .addGroup(Crear_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Crear_UsuarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Crear_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Crear_UsuarioLayout.createSequentialGroup()
                                .addGroup(Crear_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Crear_UsuarioLayout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tf_contra, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(Crear_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Crear_UsuarioLayout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(tf_userN))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Crear_UsuarioLayout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(Crear_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(Crear_UsuarioLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(js_cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(Crear_UsuarioLayout.createSequentialGroup()
                                        .addGroup(Crear_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel6))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(Crear_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(js_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tf_carrera)))))
                            .addGroup(Crear_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Crear_UsuarioLayout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tf_lugar))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Crear_UsuarioLayout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addGap(18, 18, 18)
                                    .addComponent(cb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(Crear_UsuarioLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        Crear_UsuarioLayout.setVerticalGroup(
            Crear_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Crear_UsuarioLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(Crear_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_carrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Crear_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addComponent(tf_userN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(js_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Crear_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(tf_contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(js_cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Crear_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_lugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(Crear_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jLabel11.setText("Nombre:");

        jLabel12.setText("Contraseña:");

        jLabel13.setText("N Cuenta: ");

        jLabel14.setText("Edad: ");

        jLabel15.setText("Carrera:");

        jLabel16.setText("Lugar de Nacimiento:");

        jLabel17.setText("Usuario: ");

        js_cuentaM.setModel(new javax.swing.SpinnerNumberModel());

        jButton6.setText("Modificar");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        jt_tutores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Carrera", "Edad", "Cuenta", "Usuario", "Contraseña", "Lugar Nacimiento", "Ganancias", "Nivel enseñanza", "Tutorias dadas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jt_tutores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_tutoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jt_tutores);

        jLabel19.setText("Nivel de enseñanza");

        jButton7.setText("Dar Tutoria");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        jButton14.setText("Logout");
        jButton14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton14MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout TutoresFrameLayout = new javax.swing.GroupLayout(TutoresFrame.getContentPane());
        TutoresFrame.getContentPane().setLayout(TutoresFrameLayout);
        TutoresFrameLayout.setHorizontalGroup(
            TutoresFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TutoresFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TutoresFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TutoresFrameLayout.createSequentialGroup()
                        .addGroup(TutoresFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TutoresFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(TutoresFrameLayout.createSequentialGroup()
                                    .addComponent(jLabel17)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tf_userM))
                                .addGroup(TutoresFrameLayout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tf_nombreM, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(TutoresFrameLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_contraM, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(TutoresFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(TutoresFrameLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(71, 71, 71)
                                .addComponent(tf_carreraM, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(270, 270, 270))
                            .addGroup(TutoresFrameLayout.createSequentialGroup()
                                .addGroup(TutoresFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13))
                                .addGap(59, 59, 59)
                                .addGroup(TutoresFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(js_edadM, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(js_cuentaM, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55))))
                    .addGroup(TutoresFrameLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_lugarM, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(js_enseñanza, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(353, 353, 353))))
            .addGroup(TutoresFrameLayout.createSequentialGroup()
                .addGroup(TutoresFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TutoresFrameLayout.createSequentialGroup()
                        .addGap(283, 283, 283)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(176, 176, 176)
                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TutoresFrameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 932, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 22, Short.MAX_VALUE))
        );
        TutoresFrameLayout.setVerticalGroup(
            TutoresFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TutoresFrameLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(TutoresFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel15)
                    .addComponent(tf_nombreM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_carreraM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(TutoresFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TutoresFrameLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(TutoresFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel17)
                            .addComponent(tf_userM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(js_edadM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(TutoresFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(tf_contraM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(js_cuentaM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(TutoresFrameLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(TutoresFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tf_lugarM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(js_enseñanza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(TutoresFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel18.setText("Nombre:");

        jLabel20.setText("Contraseña:");

        jLabel21.setText("N Cuenta: ");

        jLabel22.setText("Edad: ");

        jLabel23.setText("Carrera:");

        jLabel24.setText("Lugar de Nacimiento:");

        jLabel25.setText("Usuario: ");

        js_cuentaM1.setModel(new javax.swing.SpinnerNumberModel());

        jButton8.setText("Modificar");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        jt_normal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Carrera", "Edad", "Cuenta", "Usuario", "Contraseña", "Lugar Nacimiento", "Nivel aprendizaje"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jt_normal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_normalMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jt_normal);

        jLabel26.setText("Nivel de Aprendizaje");

        jButton9.setText("Ver examenes");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        jButton5.setText("Reservar Tutoria");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout NormalFrameLayout = new javax.swing.GroupLayout(NormalFrame.getContentPane());
        NormalFrame.getContentPane().setLayout(NormalFrameLayout);
        NormalFrameLayout.setHorizontalGroup(
            NormalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NormalFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NormalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NormalFrameLayout.createSequentialGroup()
                        .addGroup(NormalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(NormalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(NormalFrameLayout.createSequentialGroup()
                                    .addComponent(jLabel25)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tf_userM1))
                                .addGroup(NormalFrameLayout.createSequentialGroup()
                                    .addComponent(jLabel18)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tf_nombreM1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(NormalFrameLayout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_contraM1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(NormalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(NormalFrameLayout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(71, 71, 71)
                                .addComponent(tf_carreraM1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(270, 270, 270))
                            .addGroup(NormalFrameLayout.createSequentialGroup()
                                .addGroup(NormalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel21))
                                .addGap(59, 59, 59)
                                .addGroup(NormalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(js_edadM1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(js_cuentaM1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55))))
                    .addGroup(NormalFrameLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 932, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 22, Short.MAX_VALUE))
                    .addGroup(NormalFrameLayout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_lugarM1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(js_enseñanza1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(353, 353, 353))))
            .addGroup(NormalFrameLayout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        NormalFrameLayout.setVerticalGroup(
            NormalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NormalFrameLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(NormalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel23)
                    .addComponent(tf_nombreM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_carreraM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(NormalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NormalFrameLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(NormalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(jLabel25)
                            .addComponent(tf_userM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(js_edadM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(NormalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20)
                            .addComponent(tf_contraM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(js_cuentaM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(NormalFrameLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(NormalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(tf_lugarM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(js_enseñanza1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(NormalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jt_examenes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Clase", "Tema"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jt_examenes);

        jButton10.setText("Hacer Examen");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Examenes", jPanel1);

        jt_pasados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Clase", "Tema", "Puntaje"
            }
        ));
        jScrollPane4.setViewportView(jt_pasados);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Examenes Pasados", jPanel2);

        javax.swing.GroupLayout ExamenesLayout = new javax.swing.GroupLayout(Examenes.getContentPane());
        Examenes.getContentPane().setLayout(ExamenesLayout);
        ExamenesLayout.setHorizontalGroup(
            ExamenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExamenesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        ExamenesLayout.setVerticalGroup(
            ExamenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExamenesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jt_tutorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Clase", "Tema", "Tutor", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jt_tutorias);

        jLabel27.setText("Tutorias Disponibles: ");

        jLabel28.setText("Nueva Tutoria:");

        jLabel29.setText("Clase:");

        jLabel30.setText("Tema:");

        jLabel31.setText("Tutor:");

        jLabel32.setText("Fecha:");

        jLabel33.setText("Aula:");

        cb_tutor.setModel(new DefaultComboBoxModel());

        js_aula.setModel(new javax.swing.SpinnerNumberModel());

        jButton11.setText("Seleccionar");
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });

        jButton12.setText("Crear tutoria");
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ReservarLayout = new javax.swing.GroupLayout(Reservar.getContentPane());
        Reservar.getContentPane().setLayout(ReservarLayout);
        ReservarLayout.setHorizontalGroup(
            ReservarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReservarLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(ReservarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ReservarLayout.createSequentialGroup()
                        .addGroup(ReservarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel28)
                            .addComponent(jLabel27)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ReservarLayout.createSequentialGroup()
                                .addGroup(ReservarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ReservarLayout.createSequentialGroup()
                                        .addComponent(jLabel30)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tf_tema, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(ReservarLayout.createSequentialGroup()
                                        .addComponent(jLabel33)
                                        .addGap(18, 18, 18)
                                        .addComponent(js_aula, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(96, 96, 96)
                                .addGroup(ReservarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ReservarLayout.createSequentialGroup()
                                        .addComponent(jLabel32)
                                        .addGap(15, 15, 15)
                                        .addComponent(dc_fecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(15, 15, 15))
                                    .addGroup(ReservarLayout.createSequentialGroup()
                                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addContainerGap(40, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReservarLayout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_clase, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel31)
                        .addGap(18, 18, 18)
                        .addComponent(cb_tutor, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))))
            .addGroup(ReservarLayout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(jButton11)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        ReservarLayout.setVerticalGroup(
            ReservarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReservarLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel27)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28)
                .addGap(23, 23, 23)
                .addGroup(ReservarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ReservarLayout.createSequentialGroup()
                        .addGroup(ReservarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(jLabel31)
                            .addComponent(tf_clase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_tutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ReservarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(jLabel32)
                            .addComponent(tf_tema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(dc_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(ReservarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ReservarLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(ReservarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(js_aula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ReservarLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jt_misTutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Clase", "Tema", "Aula"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jt_misTutos);

        jLabel34.setText("Seleccione Tutoria:");

        jButton13.setText("Dar Tutoria");
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton13MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout DarTutoriaLayout = new javax.swing.GroupLayout(DarTutoria.getContentPane());
        DarTutoria.getContentPane().setLayout(DarTutoriaLayout);
        DarTutoriaLayout.setHorizontalGroup(
            DarTutoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DarTutoriaLayout.createSequentialGroup()
                .addGroup(DarTutoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DarTutoriaLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(DarTutoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel34)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(DarTutoriaLayout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(jButton13)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        DarTutoriaLayout.setVerticalGroup(
            DarTutoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DarTutoriaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel34)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton13)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Crear Cuenta");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Login");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setText("Crear Examen");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jLabel1.setText("Usuario:");

        jLabel2.setText("Contraseña");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_user)
                            .addComponent(pf_contra))
                        .addGap(41, 41, 41)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jButton1)
                        .addGap(51, 51, 51)
                        .addComponent(jButton3)
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pf_contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jButton2)))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        String nombre,user,contra,carrera,lugar,tipo;
        int cuenta,edad;
        try {
            nombre=tf_nombre.getText();
            user=tf_userN.getText();
            contra=tf_contra.getText();
            carrera=tf_carrera.getText();
            lugar=tf_lugar.getText();
            cuenta=(int)js_cuenta.getValue();
            edad=(int)js_edad.getValue();
            tipo=cb_tipo.getSelectedItem().toString();
            if(tipo.equals("Tutor"))
            {
                int nivel;
                nivel=Integer.parseInt(JOptionPane.showInputDialog("nivel de ensenanza del tutor: "));
                Tutor t=new Tutor(0, nivel, nombre, carrera, lugar, user, contra, cuenta, edad);
                alumnos.add(t);
            }
            else
            {
                int nivel;
                nivel=Integer.parseInt(JOptionPane.showInputDialog("nivel de aprendizaje del estudiante: "));
                Normal n=new Normal(nivel, 0, nombre, carrera, lugar, user, contra, cuenta, edad);
                alumnos.add(n);
            }
                JOptionPane.showMessageDialog(this, "Se creo el usuario exitosamente");
                Crear_Usuario.setVisible(false);
                tf_userN.setText("");
                tf_contra.setText("");
                tf_nombre.setText("");
                tf_carrera.setText("");
                tf_lugar.setText("");
                js_cuenta.setValue(0);
                js_edad.setValue(0);
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un error en el ingreso de datos");
        }
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        String user,contra;
        try {
            user=tf_user.getText();
            contra=pf_contra.getText();
            boolean login=false;
            int puntero=0;
            for (int i = 0; i < alumnos.size(); i++) {
                if (alumnos.get(i).getUser().equals(user)&&alumnos.get(i).getContra().equals(contra))
                {
                    login=true;
                    puntero=i;
                }
            }
            if(alumnos.get(puntero) instanceof Tutor && login)
            {
                TutoresFrame.setVisible(true);
                TutoresFrame.pack();
                for (int i = 0; i < alumnos.size(); i++) {
                    if(alumnos.get(i) instanceof Tutor)
                    {
                        Tutor t= (Tutor)alumnos.get(i);
                        Object[] newrow = {
                            t.getNombre(),
                            t.getCarrera(),
                            t.getEdad(),
                            t.getCuenta(),
                            t.getUser(),
                            t.getContra(),
                            t.getLugar(),
                            t.getGanancias(),
                            t.getNivel(),
                            t.getTutorias()
                        };
                        DefaultTableModel modelo=(DefaultTableModel) jt_tutores.getModel();
                        modelo.addRow(newrow);
                        jt_tutores.setModel(modelo);
                    }
                }
            }
            else if(alumnos.get(puntero) instanceof Normal && login)
            {
                NormalFrame.setVisible(true);
                NormalFrame.pack();
                for (int i = 0; i < alumnos.size(); i++) {
                    if(alumnos.get(i) instanceof Normal)
                    {
                        Normal t= (Normal)alumnos.get(i);
                        Object[] newrow = {
                            t.getNombre(),
                            t.getCarrera(),
                            t.getEdad(),
                            t.getCuenta(),
                            t.getUser(),
                            t.getContra(),
                            t.getLugar(),
                            t.getNivel()
                        };
                        DefaultTableModel modelo=(DefaultTableModel) jt_normal.getModel();
                        modelo.addRow(newrow);
                        jt_normal.setModel(modelo);
                    }
                }
            }
            
            else{
                JOptionPane.showMessageDialog(this, "Usuario o contrasena equivocada");
            }
            tf_user.setText("");
            pf_contra.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Mala ingresion de datos");
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        String clase,tema;
        int puntaje=0;
        clase=JOptionPane.showInputDialog("Ingrese la clase del examen: ");
        tema=JOptionPane.showInputDialog("Ingrese el tema del examen: ");
        Examen e=new Examen(clase, tema, puntaje);
        for (int i = 0; i < alumnos.size(); i++) {
            if(alumnos.get(i) instanceof Normal)
            {
                ((Normal)alumnos.get(i)).getExamenes().add(e);
            }
        }
        JOptionPane.showMessageDialog(this, "Se agrego el examen exitosamente");
    }//GEN-LAST:event_jButton3MouseClicked

    private void jt_tutoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_tutoresMouseClicked
        // TODO add your handling code here
        if(jt_tutores.getSelectedRow()>=0)
        {
            tf_nombreM.setText((String)jt_tutores.getValueAt(jt_tutores.getSelectedRow(), 0));
            tf_carreraM.setText((String)jt_tutores.getValueAt(jt_tutores.getSelectedRow(), 1));
            js_edadM.setValue((Integer)jt_tutores.getValueAt(jt_tutores.getSelectedRow(), 2));
            js_cuentaM.setValue((Integer)jt_tutores.getValueAt(jt_tutores.getSelectedRow(), 3));
            tf_userM.setText((String)jt_tutores.getValueAt(jt_tutores.getSelectedRow(), 4));
            tf_contraM.setText((String)jt_tutores.getValueAt(jt_tutores.getSelectedRow(), 5));
            tf_lugarM.setText((String)jt_tutores.getValueAt(jt_tutores.getSelectedRow(), 6));
            js_enseñanza.setValue((Integer)jt_tutores.getValueAt(jt_tutores.getSelectedRow(), 7));
        }
    }//GEN-LAST:event_jt_tutoresMouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        DefaultTableModel modelo=(DefaultTableModel) jt_tutores.getModel();
        modelo.setValueAt(tf_nombre.getText(),jt_tutores.getSelectedRow(), 0);  
        modelo.setValueAt(tf_carreraM.getText(),jt_tutores.getSelectedRow(), 1);
        modelo.setValueAt((int)js_edadM.getValue(),jt_tutores.getSelectedRow(), 2);
        modelo.setValueAt((int)js_cuentaM.getValue(),jt_tutores.getSelectedRow(), 3);
        modelo.setValueAt(tf_userM.getText(),jt_tutores.getSelectedRow(), 4);
        modelo.setValueAt(tf_contraM.getText(),jt_tutores.getSelectedRow(), 5);
        modelo.setValueAt(tf_lugarM.getText(),jt_tutores.getSelectedRow(), 6);
        modelo.setValueAt((int)js_enseñanza.getValue(),jt_tutores.getSelectedRow(), 7);
        jt_tutores.setModel(modelo);
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        // TODO add your handling code here:
        DefaultTableModel modelo=(DefaultTableModel) jt_normal.getModel();
        modelo.setValueAt(tf_nombre.getText(),jt_normal.getSelectedRow(), 0);  
        modelo.setValueAt(tf_carreraM.getText(),jt_normal.getSelectedRow(), 1);
        modelo.setValueAt((int)js_edadM.getValue(),jt_normal.getSelectedRow(), 2);
        modelo.setValueAt((int)js_cuentaM.getValue(),jt_normal.getSelectedRow(), 3);
        modelo.setValueAt(tf_userM.getText(),jt_normal.getSelectedRow(), 4);
        modelo.setValueAt(tf_contraM.getText(),jt_normal.getSelectedRow(), 5);
        modelo.setValueAt(tf_lugarM.getText(),jt_normal.getSelectedRow(), 6);
        modelo.setValueAt((int)js_enseñanza.getValue(),jt_normal.getSelectedRow(), 7);
        jt_normal.setModel(modelo);
    }//GEN-LAST:event_jButton8MouseClicked

    private void jt_normalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_normalMouseClicked
        // TODO add your handling code here:
        if(jt_tutores.getSelectedRow()>=0)
        {
            tf_nombreM1.setText((String)jt_normal.getValueAt(jt_normal.getSelectedRow(), 0));
            tf_carreraM1.setText((String)jt_normal.getValueAt(jt_normal.getSelectedRow(), 1));
            js_edadM1.setValue((Integer)jt_normal.getValueAt(jt_normal.getSelectedRow(), 2));
            js_cuentaM1.setValue((Integer)jt_normal.getValueAt(jt_normal.getSelectedRow(), 3));
            tf_userM1.setText((String)jt_normal.getValueAt(jt_normal.getSelectedRow(), 4));
            tf_contraM1.setText((String)jt_normal.getValueAt(jt_normal.getSelectedRow(), 5));
            tf_lugarM1.setText((String)jt_normal.getValueAt(jt_normal.getSelectedRow(), 6));
            js_enseñanza1.setValue((Integer)jt_normal.getValueAt(jt_normal.getSelectedRow(), 7));
        }
    }//GEN-LAST:event_jt_normalMouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        // TODO add your handling code here:
        Examenes.setVisible(true);
        Examenes.pack();
        for (int i = 0; i < ((Normal)actual).getExamenes().size(); i++) {
            Examen e = ((Normal)actual).getExamenes().get(i);
            Object[] newrow = {
                e.getClase(),
                e.getTema()
            };
            DefaultTableModel modelo=(DefaultTableModel) jt_examenes.getModel();
            modelo.addRow(newrow);
            jt_examenes.setModel(modelo);
        }
        for (int i = 0; i < ((Normal)actual).getExamenesPasados().size(); i++) {
            Examen e = ((Normal)actual).getExamenesPasados().get(i);
            Object [] newrow = {
                e.getClase(),
                e.getTema(),
                e.getPuntaje()
            };
            DefaultTableModel modelo=(DefaultTableModel) jt_examenes.getModel();
            modelo.addRow(newrow);
            jt_examenes.setModel(modelo);
        }
        
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        Reservar.setVisible(true);
        Reservar.pack();
        for (int i = 0; i < tutorias.size(); i++) {
            Tutoria t= tutorias.get(i);
            Object[] newrow = {
                t.getClase(),
                t.getTema(),
                t.getTutor(),
                t.getFecha()
            };
            DefaultTableModel modelo=(DefaultTableModel) jt_tutorias.getModel();
            modelo.addRow(newrow);
            jt_tutorias.setModel(modelo);
        }
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (int i = 0; i < alumnos.size(); i++) {
            if(alumnos.get(i) instanceof Tutor)
            {
                modelo.addElement(alumnos.get(i));
            }
        }
        cb_tutor.setModel(modelo);
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        // TODO add your handling code here:
        if(jt_examenes.getSelectedRow()>=0)
        {
            Examen e=((Normal)actual).getExamenes().get(jt_examenes.getSelectedRow());
            int r=1+rand.nextInt(100);
            e.setConocimiento(r);
            if(((Normal)actual).getConocimiento()>=e.getConocimiento())
            {
                JOptionPane.showMessageDialog(this, "paso el examen");
                e.setPuntaje(r);
                ((Normal)actual).getExamenesPasados().add(e);
                ((Normal)actual).getExamenes().remove(jt_examenes.getSelectedRow());
                DefaultTableModel modelo=(DefaultTableModel) jt_examenes.getModel();
                modelo.removeRow(jt_examenes.getSelectedRow());
                jt_examenes.setModel(modelo);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Reprobo el examen");
            }
            
        }
        else
        {
            JOptionPane.showMessageDialog(this, "No selecciono un examen");
        }
    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        // TODO add your handling code here:
        if(jt_tutorias.getSelectedRow()>=0)
        {
            Tutoria t=tutorias.get(jt_tutorias.getSelectedRow());
            t.getAlumnos().add(actual);
            Reservar.setVisible(false);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "No selecciono una tutoria");
        }
    }//GEN-LAST:event_jButton11MouseClicked

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
        // TODO add your handling code here:
        String clase,tema;
        int aula;
        Date fecha;
        Tutor t;
        clase=tf_clase.getText();
        tema=tf_tema.getText();
        aula=(int)js_aula.getValue();
        fecha=dc_fecha.getDate();
        t=(Tutor)cb_tutor.getSelectedItem();
        Tutoria tu=new Tutoria(t, aula, clase, tema, fecha);
        tu.getAlumnos().add(actual);
        t.getClases().add(tu);
        tutorias.add(tu);
        JOptionPane.showMessageDialog(this, "Se creo la tutoria exitosamente");
        Reservar.setVisible(false);
        tf_clase.setText("");
        tf_tema.setText("");
        js_aula.setValue(0);
        
    }//GEN-LAST:event_jButton12MouseClicked

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
        DarTutoria.setVisible(true);
        DarTutoria.pack();
        for (int i = 0; i < ((Tutor)actual).getClases().size(); i++) {
            Tutoria t = ((Tutor)actual).getClases().get(i);
            Object [] newrow = {
                t.getClase(),
                t.getTema(),
                t.getAula()
            };
            DefaultTableModel modelo=(DefaultTableModel) jt_misTutos.getModel();
            modelo.addRow(newrow);
            jt_misTutos.setModel(modelo);
        }
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseClicked
        // TODO add your handling code here:
        if(jt_misTutos.getSelectedRow()>=0)
        {
            actual.DarTuto();
            ((Tutor)actual).getClases().remove(jt_misTutos.getSelectedRow());
             for (int i = 0; i < ((Tutor)actual).getClases().get(jt_misTutos.getSelectedRow()).getAlumnos().size(); i++) {
                 ((Tutor)actual).getClases().get(jt_misTutos.getSelectedRow()).getAlumnos().get(i).DarTuto();
                 JOptionPane.showMessageDialog(this, "Se dio la tutoria exitosamente");
                 DarTutoria.setVisible(false);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "No se selecciono una tutoria");
        }
    }//GEN-LAST:event_jButton13MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        Crear_Usuario.setVisible(true);
        Crear_Usuario.pack();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton14MouseClicked
        // TODO add your handling code here:
        TutoresFrame.setVisible(false);
        
    }//GEN-LAST:event_jButton14MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tutorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tutorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tutorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tutorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tutorias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Crear_Usuario;
    private javax.swing.JDialog DarTutoria;
    private javax.swing.JDialog Examenes;
    private javax.swing.JDialog NormalFrame;
    private javax.swing.JDialog Reservar;
    private javax.swing.JDialog TutoresFrame;
    private javax.swing.JComboBox<String> cb_tipo;
    private javax.swing.JComboBox<String> cb_tutor;
    private com.toedter.calendar.JDateChooser dc_fecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JSpinner js_aula;
    private javax.swing.JSpinner js_cuenta;
    private javax.swing.JSpinner js_cuentaM;
    private javax.swing.JSpinner js_cuentaM1;
    private javax.swing.JSpinner js_edad;
    private javax.swing.JSpinner js_edadM;
    private javax.swing.JSpinner js_edadM1;
    private javax.swing.JSpinner js_enseñanza;
    private javax.swing.JSpinner js_enseñanza1;
    private javax.swing.JTable jt_examenes;
    private javax.swing.JTable jt_misTutos;
    private javax.swing.JTable jt_normal;
    private javax.swing.JTable jt_pasados;
    private javax.swing.JTable jt_tutores;
    private javax.swing.JTable jt_tutorias;
    private javax.swing.JPasswordField pf_contra;
    private javax.swing.JTextField tf_carrera;
    private javax.swing.JTextField tf_carreraM;
    private javax.swing.JTextField tf_carreraM1;
    private javax.swing.JTextField tf_clase;
    private javax.swing.JTextField tf_contra;
    private javax.swing.JTextField tf_contraM;
    private javax.swing.JTextField tf_contraM1;
    private javax.swing.JTextField tf_lugar;
    private javax.swing.JTextField tf_lugarM;
    private javax.swing.JTextField tf_lugarM1;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_nombreM;
    private javax.swing.JTextField tf_nombreM1;
    private javax.swing.JTextField tf_tema;
    private javax.swing.JTextField tf_user;
    private javax.swing.JTextField tf_userM;
    private javax.swing.JTextField tf_userM1;
    private javax.swing.JTextField tf_userN;
    // End of variables declaration//GEN-END:variables

    ArrayList<Alumnos> alumnos=new ArrayList<>();
    ArrayList<Tutoria> tutorias=new ArrayList<>();
    Alumnos actual;
    static Random rand=new Random();
}
